Repository UpendoVentures/HubSpot-EasyDnnNews-Blog-Migrator, pull requests merged in 2024-05, with the labels that each got.

#33 Fix url images
  Modules/HubSpotEasyDnnNewsBlogMigrator/Controllers/EasyDNNNewsController.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/Contract/IEasyDNNNewsRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/EasyDNNNewsRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/UpendoVentures.Modules.HubSpotEasyDnnNewsBlogMigrator.csproj
  Modules/HubSpotEasyDnnNewsBlogMigrator/ViewModels/ReplaceImageUrlParams.cs
Labels: enhancement

#34 Releasing 1.4.0
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator_Symbols.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/Properties/AssemblyInfo.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/ReleaseNotes.txt
Labels: task

#35 Fixes
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/packages.config
Labels: bug

#36 Releasing 1.4.1
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator_Symbols.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/Properties/AssemblyInfo.cs
Labels: task

#37 Update HubspotRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/HubspotRepository.cs
Labels: bug

#39 Fix blog links
  Modules/HubSpotEasyDnnNewsBlogMigrator/Constants/Constant.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Controllers/EasyDNNNewsController.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/Contract/IEasyDNNNewsRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/EasyDNNNewsRepository.cs
Labels: bug, enhancement

#40 Tasks/release 01.05.00
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator_Symbols.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/Properties/AssemblyInfo.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/ReleaseNotes.txt
Labels: task
