Repository UpendoVentures/HubSpot-EasyDnnNews-Blog-Migrator, pull requests merged in 2024-04, with the labels that each got.

#23 Improvements larger blogs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Models/HubSpotEasyDNNNews.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Providers/DataProviders/SqlDataProvider/01.00.00.SqlDataProvider
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/HubspotRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/UpendoVentures.Modules.HubSpotEasyDnnNewsBlogMigrator.csproj
  Modules/HubSpotEasyDnnNewsBlogMigrator/client-app/src/components/HomeItem.vue
Labels: bug, enhancement

#24 Tasks/release 1.1.0 prep
  Modules/HubSpotEasyDnnNewsBlogMigrator/Constants/Constant.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Controllers/HubspotController.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator_Symbols.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/Properties/AssemblyInfo.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/ReleaseNotes.txt
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/EasyDNNNewsRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/HubspotRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Services/ResxController.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Services/ServiceRouteMapper.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/ViewModels/BlogResponse.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/client-app/package-lock.json
Labels: task

#25 Added some debugging statements
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/EasyDNNNewsGenericRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/HubspotRepository.cs
Labels: enhancement

#28 Improvements larger blogs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/HubspotRepository.cs
Labels: bug

#29 Auth access token
  Modules/HubSpotEasyDnnNewsBlogMigrator/App_LocalResources/View.resx
  Modules/HubSpotEasyDnnNewsBlogMigrator/Constants/Constant.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Controllers/HubspotController.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/Contract/IHubspotRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/HubspotRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/UpendoVentures.Modules.HubSpotEasyDnnNewsBlogMigrator.csproj
  Modules/HubSpotEasyDnnNewsBlogMigrator/ViewModels/HubspotAccessTokenSetting.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/client-app/src/components/HomeItem.vue
  Modules/HubSpotEasyDnnNewsBlogMigrator/client-app/src/components/HubSpotAccessTokenSettings.vue
Labels: enhancement

#30 Tasks/release 1.2.0
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator_Symbols.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/Properties/AssemblyInfo.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/ReleaseNotes.txt
Labels: task

#31 Summary hubspot images
  Modules/HubSpotEasyDnnNewsBlogMigrator/App_LocalResources/View.resx
  Modules/HubSpotEasyDnnNewsBlogMigrator/Constants/Constant.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Controllers/HubspotController.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/Contract/IHubspotRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/Repository/HubspotRepository.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/UpendoVentures.Modules.HubSpotEasyDnnNewsBlogMigrator.csproj
  Modules/HubSpotEasyDnnNewsBlogMigrator/ViewModels/ImageInHubspot.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/client-app/src/components/HomeItem.vue
  Modules/HubSpotEasyDnnNewsBlogMigrator/client-app/src/components/MigrateImage.vue
Labels: enhancement

#32 Tasks/release 1.3.0
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/HubSpotEasyDnnNewsBlogMigrator_Symbols.dnn
  Modules/HubSpotEasyDnnNewsBlogMigrator/Properties/AssemblyInfo.cs
  Modules/HubSpotEasyDnnNewsBlogMigrator/ReleaseNotes.txt
Labels: enhancement
